services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: bookshopdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SHARED_BUFFERS: 250MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 500MB
      POSTGRES_WORK_MEM: 28MB
    ports:
      - "5435:5432"
    volumes:
      - bookshopdb_data:/var/lib/postgresql/data
    command: >
      postgres
      -c max_connections=1000
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bookshop-network


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bookshop.com
      PGADMIN_DEFAULT_PASSWORD: admin           
      PGADMIN_CONFIG_SERVER_MODE: 'False'      
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"                              
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy  
    networks:
     - bookshop-network   


  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "UserID=postgres;Host=postgres;port=5432;database=bookshopdb;Password=postgres"
     #hybridcache
     # ConnectionStrings__Redis: "redis:6379"
      Jwt__Key: "bookshop-super-secret-jwt-key-32chars!!"
      Jwt__Issuer: "bookshop-api"
      Jwt__Audience: "bookshop-client"
      Jwt__ExpiresInMinutes: "1440"
      AdminSeed__Email: "admin@admin"
      AdminSeed__Password: "admin"
    depends_on:
      postgres:
        condition: service_healthy
     # redis:
     #   condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    networks:
      - bookshop-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: on-failure
    networks:
      - bookshop-network

#пока не используется
  #redis:
   # image: redis:7-alpine
    #ports:
     # - "6379:6379"
    #volumes:
     # - redis_data:/data
    #restart: unless-stopped
    #networks:
     # - bookshop-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    networks:
      - bookshop-network


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_QUIET_MODE=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - bookshop-network
  dufs:
    image: sigoden/dufs:latest
    container_name: resourseserver-1
    ports:
      - "5034:5000" 
    volumes:
      - dufs_resourseserver:/var/lib/resourses 
    command: var/lib/resourses  -A
    restart: unless-stopped
    networks:
      - bookshop-network
      

volumes:
  bookshopdb_data:
  prometheus_data:
  grafana_data:
  pgadmin_data:
  dufs_resourseserver:
 # redis_data:

networks:
  bookshop-network:
    driver: bridge

