services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: bookshopdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SHARED_BUFFERS: 100MB     
      POSTGRES_EFFECTIVE_CACHE_SIZE: 150MB
      POSTGRES_WORK_MEM: 16MB   
    ports:
      - "5435:5432"
    volumes:
      - bookshoopdb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  bookshoopdb_data: